# ─────────────────────────────────────────────
# WHITEBOX HYPRLOCK
# ─────────────────────────────────────────────

general {
    hide_cursor = true
    grace = 0
}


# ─────────────────────────────────────────────
# BACKGROUND
# ─────────────────────────────────────────────

background {
    monitor =

    path = /home/subaru/whitebox/home/dots/hypr/wallpapers/current

    blur_passes = 3
    blur_size = 8

    brightness = 0.68
    contrast = 1.05
    vibrancy = 0.12
    vibrancy_darkness = 0.0
}


# ─────────────────────────────────────────────
# CLOCK
# ─────────────────────────────────────────────

label {
    monitor =

    text = $TIME

    color = rgb(c6d0f5)

    font_size = 72
    font_family = sans-serif

    position = 0, 250

    halign = center
    valign = center
}


# ─────────────────────────────────────────────
# DATE
# ─────────────────────────────────────────────

label {
    monitor =

    text = cmd[update:1000] date +"%A, %B %d"

    color = rgb(b5bfe2)

    font_size = 18
    font_family = sans-serif

    position = 0, 180

    halign = center
    valign = center
}

# ─────────────────────────────────────────────
# USERNAME
# ─────────────────────────────────────────────

label {
    monitor =

    text = subaru

    color = rgb(c6d0f5)

    font_size = 20
    font_family = sans-serif

    position = 0, -35

    halign = center
    valign = center
}


# ─────────────────────────────────────────────
# PASSWORD
# ─────────────────────────────────────────────

input-field {
    monitor =

    size = 340, 54

    outline_thickness = 2

    outer_color = rgb(8caaee)
    inner_color = rgb(414559)

    font_color = rgb(c6d0f5)

    check_color = rgb(a6d189)
    fail_color = rgb(e78284)

    placeholder_text = <span foreground="##a5adce">Enter password...</span>

    fail_text = <span foreground="##e78284">Authentication failed</span>

    dots_size = 0.22
    dots_spacing = 0.28
    dots_center = true

    fade_on_empty = false

    rounding = 14

    position = 0, -105

    halign = center
    valign = center
}
