# ----- Theme -----
#include frappe.conf


# ----- Font -----
font_family JetBrainsMono Nerd Font
font_size 11


# ----- Cursor -----
cursor_shape beam


# ----- Integration -----
allow_hyperlinks yes


# ----- Disable close confirmation -----
confirm_os_window_close 0

